version: "3.2"

services:
  n4l-be:
    build: .
    container_name: n4l-be
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://codehq:codehq@mongodb:27017/todo-app?authSource=admin&w=1
      - PORT = "3001"
      - CORS_ORIGIN = "http://localhost:4200"

  mongodb:
    image: "mongo:6.0.7"
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=codehq
      - MONGO_INITDB_ROOT_PASSWORD=codehq

  rabbitmq:
    image: "rabbitmq:3.12.1-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=codehq
      - RABBITMQ_DEFAULT_PASS=codehq

networks:
  default:
    driver: bridge
